### ISSUE TITLE
dependencies error

### ISSUE THREAD

**Issue by fivesmallq** [codeborne/play-logger#1]
play version: 1.4.x

play dependencies file:
```yaml
# Application dependencies

require:
    - play
    - play-codeborne -> logger 1.15

repositories:
    - play-logger:
      type: http
      artifact: https://repo.codeborne.com/play-logger/logger-1.15.zip
      contains:
        - play-codeborne -> *
```

play deps log:
```
~ Oops, malformed dependencies.yml descriptor:
~
~ 	Parsing error in play-logger: check the format and the indentation.
~
Exception in thread "main" java.lang.RuntimeException: Malformed dependencies.yml descriptor
	at play.deps.SettingsParser.parse(SettingsParser.java:90)
	at play.deps.DependenciesManager.configure(DependenciesManager.java:377)
	at play.deps.DependenciesManager.resolve(DependenciesManager.java:337)
	at play.deps.DependenciesManager.main(DependenciesManager.java:39)
```

**Comment by asolntsev** [comment]
@fivesmallq Thank you for reporting the problem!
Actually just indentation should be fixed:

```yml
# Application dependencies

require:
    - play
    - play-codeborne -> logger 1.15

repositories:
    - play-logger:
          type: http
          artifact: https://repo.codeborne.com/play-logger/logger-1.15.zip
          contains:
              - play-codeborne -> *
```
